"""
Pydantic models for backtesting API.
"""

from datetime import datetime, date
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field


class BacktestRequest(BaseModel):
    """Request body for running a backtest."""
    symbols: List[str] = Field(..., description="List of symbols to backtest")
    start_date: date = Field(..., description="Backtest start date")
    end_date: date = Field(..., description="Backtest end date")
    initial_capital: float = Field(default=100000, description="Starting capital")
    strategy: str = Field(default="simple_rsi", description="Strategy to use")
    strategy_params: Dict[str, Any] = Field(default_factory=dict, description="Strategy parameters")
    position_size_pct: float = Field(default=10.0, description="Position size as % of portfolio")


class Signal(BaseModel):
    """A trading signal generated by a strategy."""
    symbol: str
    action: str  # "BUY" or "SELL"
    timestamp: datetime
    reason: str
    confidence: float = 1.0


class SimulatedTrade(BaseModel):
    """A simulated trade from backtesting."""
    symbol: str
    side: str  # "BUY" or "SELL"
    quantity: float
    entry_price: float
    entry_time: datetime
    exit_price: Optional[float] = None
    exit_time: Optional[datetime] = None
    pnl: Optional[float] = None
    pnl_pct: Optional[float] = None
    reason: str = ""


class EquityPoint(BaseModel):
    """A point on the equity curve."""
    timestamp: datetime
    equity: float
    cash: float
    positions_value: float


class PerformanceMetricsResult(BaseModel):
    """Performance metrics from a backtest."""
    # Basic stats
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float

    # Returns
    total_return_pct: float
    annualized_return_pct: float

    # Risk metrics
    max_drawdown_pct: float
    sharpe_ratio: float
    sortino_ratio: float

    # Trade metrics
    average_win: float
    average_loss: float
    profit_factor: float
    expectancy: float

    # Comparison
    benchmark_return_pct: Optional[float] = None
    alpha: Optional[float] = None


class BacktestResult(BaseModel):
    """Complete backtest results."""
    # Config
    symbols: List[str]
    start_date: date
    end_date: date
    initial_capital: float
    strategy: str
    strategy_params: Dict[str, Any]

    # Results
    final_equity: float
    metrics: PerformanceMetricsResult
    equity_curve: List[EquityPoint]
    trades: List[SimulatedTrade]

    # Timing
    run_time_seconds: float
    bars_processed: int


class StrategyInfo(BaseModel):
    """Information about an available strategy."""
    id: str
    name: str
    description: str
    default_params: Dict[str, Any] = Field(default_factory=dict)
